apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnsmon
  namespace: dnsmon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmon
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnsmon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnsmon
subjects:
  - kind: ServiceAccount
    name: dnsmon
    namespace: dnsmon-system
