apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dnsmon
  namespace: dnsmon-system
  labels:
    app.kubernetes.io/name: dnsmon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dnsmon
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
