apiVersion: v1
kind: Service
metadata:
  name: dnsmon
  namespace: dnsmon-system
  labels:
    app.kubernetes.io/name: dnsmon
spec:
  selector:
    app.kubernetes.io/name: dnsmon
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
